import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the ROS 2 module
  ros2ModuleSidebar: [
  {
    type: 'category',
    label: 'Module 1: The Robotic Nervous System (ROS 2)',
    items: [
      'module-1-robotic-nervous-system/introduction-to-ros2',
      'module-1-robotic-nervous-system/core-concepts-nodes-topics-messages',
      'module-1-robotic-nervous-system/services-and-actions',
      'module-1-robotic-nervous-system/parameters-and-dynamic-configuration',
      'module-1-robotic-nervous-system/launch-files-and-composing-systems',
      'module-1-robotic-nervous-system/urdf-fundamentals',
      'module-1-robotic-nervous-system/bridging-python-ai-agents-with-rclpy',
      'module-1-robotic-nervous-system/debugging-visualization-best-practices',
    ],
  },
  {
    type: 'category',
    label: 'Module 2: The Digital Twin (Gazebo & Unity)',
    items: [
      'module-2-digital-twin/introduction-to-digital-twins',
      'module-2-digital-twin/setting-up-gazebo-with-ros2',
      'module-2-digital-twin/world-building-physics-collisions',
      'module-2-digital-twin/spawning-controlling-humanoids-gazebo',
      'module-2-digital-twin/introduction-unity-robotics',
      'module-2-digital-twin/importing-urdf-unity-rendering',
      'module-2-digital-twin/simulating-sensors-lidar-depth-imu',
      'module-2-digital-twin/comparing-gazebo-unity-best-practices',
    ],
  },
  {
  type: 'category',
  label: 'Module 3: The AI Robot Brain (NVIDIA Isaac)',
  items: [
    'module-3-ai-robot-brain/introduction-to-nvidia-isaac',
    'module-3-ai-robot-brain/setting-up-isaac-sim-ros2',
    'module-3-ai-robot-brain/photorealistic-simulation-humanoids',
    'module-3-ai-robot-brain/synthetic-data-generation',
    'module-3-ai-robot-brain/introduction-isaac-ros-packages',
    'module-3-ai-robot-brain/visual-slam-perception-isaac-ros',
    'module-3-ai-robot-brain/nav2-bipedal-navigation',
    'module-3-ai-robot-brain/best-practices-sim-optimization',
  ],
},
{
  type: 'category',
  label: 'Module 4: Vision-Language-Action (VLA)',
  items: [
    'module-4-vla/introduction-to-vla-robotics',
    'module-4-vla/voice-to-text-whisper',
    'module-4-vla/natural-language-with-llms',
    'module-4-vla/cognitive-planning-ros-actions',
    'module-4-vla/integrating-perception-vla',
    'module-4-vla/path-planning-language-goals',
    'module-4-vla/manipulation-language-commands',
    'module-4-vla/capstone-autonomous-humanoid',
  ],
},
  ],

};

export default sidebars;



